export interface Row {
  id: string;
  sendDate: string;
  name: string;
  priority: boolean;
  price: string;
  approvalStep: string;
  requirent: string;
  department: "finance" | "mechanic";
  status: "pendente" | "agendado" | "historico";
  step: "solicitacao" | "gestor" | "financeiro" | "confirmacao" | "pagamento";
}

export const rawRows: Row[] = [
  {
    id: "1",
    sendDate: "24/Junho",
    name: "Item 1",
    priority: false,
    price: "R$ 600,00 \n x 1 unidade",
    approvalStep: "1 de 2",
    requirent: "Colaborador 1",
    department: "finance",
    status: "pendente",
    step: "solicitacao",
  },
  {
    id: "2",
    sendDate: "23/Junho",
    name: "Item 2",
    priority: true,
    price: "R$ 700,00 \n x 1 unidade",
    approvalStep: "2 de 2",
    requirent: "Colaborador 2",
    department: "mechanic",
    status: "pendente",
    step: "solicitacao",
  },
  {
    id: "3",
    sendDate: "22/Junho",
    name: "Item 3",
    priority: false,
    price: "R$ 800,00 \n x 1 unidade",
    approvalStep: "1 de 2",
    requirent: "Colaborador 3",
    department: "finance",
    status: "agendado",
    step: "solicitacao",
  },
  {
    id: "4",
    sendDate: "21/Junho",
    name: "Item 4",
    priority: false,
    price: "R$ 900,00 \n x 1 unidade",
    approvalStep: "2 de 2",
    requirent: "Colaborador 4",
    department: "mechanic",
    status: "agendado",
    step: "solicitacao",
  },
  {
    id: "5",
    sendDate: "20/Junho",
    name: "Item 5",
    priority: true,
    price: "R$ 1.000,00 \n x 1 unidade",
    approvalStep: "1 de 2",
    requirent: "Colaborador 5",
    department: "finance",
    status: "historico",
    step: "solicitacao",
  },
  {
    id: "6",
    sendDate: "19/Junho",
    name: "Item 6",
    priority: false,
    price: "R$ 1.100,00 \n x 1 unidade",
    approvalStep: "2 de 2",
    requirent: "Colaborador 6",
    department: "mechanic",
    status: "historico",
    step: "solicitacao",
  },

  /* ---------- etapa: gestor ---------- */
  {
    id: "7",
    sendDate: "18/Junho",
    name: "Item 7",
    priority: false,
    price: "R$ 1.200,00 \n x 1 unidade",
    approvalStep: "1 de 2",
    requirent: "Colaborador 7",
    department: "finance",
    status: "pendente",
    step: "gestor",
  },
  {
    id: "8",
    sendDate: "17/Junho",
    name: "Item 8",
    priority: true,
    price: "R$ 1.300,00 \n x 1 unidade",
    approvalStep: "2 de 2",
    requirent: "Colaborador 8",
    department: "mechanic",
    status: "pendente",
    step: "gestor",
  },
  {
    id: "9",
    sendDate: "16/Junho",
    name: "Item 9",
    priority: false,
    price: "R$ 1.400,00 \n x 1 unidade",
    approvalStep: "1 de 2",
    requirent: "Colaborador 9",
    department: "finance",
    status: "agendado",
    step: "gestor",
  },
  {
    id: "10",
    sendDate: "15/Junho",
    name: "Item 10",
    priority: false,
    price: "R$ 1.500,00 \n x 1 unidade",
    approvalStep: "2 de 2",
    requirent: "Colaborador 10",
    department: "mechanic",
    status: "agendado",
    step: "gestor",
  },
  {
    id: "11",
    sendDate: "14/Junho",
    name: "Item 11",
    priority: true,
    price: "R$ 1.600,00 \n x 1 unidade",
    approvalStep: "1 de 2",
    requirent: "Colaborador 11",
    department: "finance",
    status: "historico",
    step: "gestor",
  },
  {
    id: "12",
    sendDate: "13/Junho",
    name: "Item 12",
    priority: false,
    price: "R$ 1.700,00 \n x 1 unidade",
    approvalStep: "2 de 2",
    requirent: "Colaborador 12",
    department: "mechanic",
    status: "historico",
    step: "gestor",
  },

  /* ---------- etapa: financeiro ---------- */
  {
    id: "13",
    sendDate: "12/Junho",
    name: "Item 13",
    priority: false,
    price: "R$ 1.800,00 \n x 1 unidade",
    approvalStep: "1 de 2",
    requirent: "Colaborador 13",
    department: "finance",
    status: "pendente",
    step: "financeiro",
  },
  {
    id: "14",
    sendDate: "11/Junho",
    name: "Item 14",
    priority: true,
    price: "R$ 1.900,00 \n x 1 unidade",
    approvalStep: "2 de 2",
    requirent: "Colaborador 14",
    department: "mechanic",
    status: "pendente",
    step: "financeiro",
  },
  {
    id: "15",
    sendDate: "10/Junho",
    name: "Item 15",
    priority: false,
    price: "R$ 2.000,00 \n x 1 unidade",
    approvalStep: "1 de 2",
    requirent: "Colaborador 15",
    department: "finance",
    status: "agendado",
    step: "financeiro",
  },
  {
    id: "16",
    sendDate: "09/Junho",
    name: "Item 16",
    priority: false,
    price: "R$ 2.100,00 \n x 1 unidade",
    approvalStep: "2 de 2",
    requirent: "Colaborador 16",
    department: "mechanic",
    status: "agendado",
    step: "financeiro",
  },
  {
    id: "17",
    sendDate: "08/Junho",
    name: "Item 17",
    priority: true,
    price: "R$ 2.200,00 \n x 1 unidade",
    approvalStep: "1 de 2",
    requirent: "Colaborador 17",
    department: "finance",
    status: "historico",
    step: "financeiro",
  },
  {
    id: "18",
    sendDate: "07/Junho",
    name: "Item 18",
    priority: false,
    price: "R$ 2.300,00 \n x 1 unidade",
    approvalStep: "2 de 2",
    requirent: "Colaborador 18",
    department: "mechanic",
    status: "historico",
    step: "financeiro",
  },

  /* ---------- etapa: confirmacao ---------- */
  {
    id: "19",
    sendDate: "06/Junho",
    name: "Item 19",
    priority: false,
    price: "R$ 2.400,00 \n x 1 unidade",
    approvalStep: "1 de 2",
    requirent: "Colaborador 19",
    department: "finance",
    status: "pendente",
    step: "confirmacao",
  },
  {
    id: "20",
    sendDate: "05/Junho",
    name: "Item 20",
    priority: true,
    price: "R$ 2.500,00 \n x 1 unidade",
    approvalStep: "2 de 2",
    requirent: "Colaborador 20",
    department: "mechanic",
    status: "pendente",
    step: "confirmacao",
  },
  {
    id: "21",
    sendDate: "04/Junho",
    name: "Item 21",
    priority: false,
    price: "R$ 2.600,00 \n x 1 unidade",
    approvalStep: "1 de 2",
    requirent: "Colaborador 21",
    department: "finance",
    status: "agendado",
    step: "confirmacao",
  },
  {
    id: "22",
    sendDate: "03/Junho",
    name: "Item 22",
    priority: false,
    price: "R$ 2.700,00 \n x 1 unidade",
    approvalStep: "2 de 2",
    requirent: "Colaborador 22",
    department: "mechanic",
    status: "agendado",
    step: "confirmacao",
  },
  {
    id: "23",
    sendDate: "02/Junho",
    name: "Item 23",
    priority: true,
    price: "R$ 2.800,00 \n x 1 unidade",
    approvalStep: "1 de 2",
    requirent: "Colaborador 23",
    department: "finance",
    status: "historico",
    step: "confirmacao",
  },
  {
    id: "24",
    sendDate: "01/Junho",
    name: "Item 24",
    priority: false,
    price: "R$ 2.900,00 \n x 1 unidade",
    approvalStep: "2 de 2",
    requirent: "Colaborador 24",
    department: "mechanic",
    status: "historico",
    step: "confirmacao",
  },

  /* ---------- etapa: pagamento ---------- */
  {
    id: "25",
    sendDate: "30/Maio",
    name: "Item 25",
    priority: false,
    price: "R$ 3.000,00 \n x 1 unidade",
    approvalStep: "1 de 2",
    requirent: "Colaborador 25",
    department: "finance",
    status: "pendente",
    step: "pagamento",
  },
  {
    id: "26",
    sendDate: "29/Maio",
    name: "Item 26",
    priority: true,
    price: "R$ 3.100,00 \n x 1 unidade",
    approvalStep: "2 de 2",
    requirent: "Colaborador 26",
    department: "mechanic",
    status: "pendente",
    step: "pagamento",
  },
  {
    id: "27",
    sendDate: "28/Maio",
    name: "Item 27",
    priority: false,
    price: "R$ 3.200,00 \n x 1 unidade",
    approvalStep: "1 de 2",
    requirent: "Colaborador 27",
    department: "finance",
    status: "agendado",
    step: "pagamento",
  },
  {
    id: "28",
    sendDate: "27/Maio",
    name: "Item 28",
    priority: false,
    price: "R$ 3.300,00 \n x 1 unidade",
    approvalStep: "2 de 2",
    requirent: "Colaborador 28",
    department: "mechanic",
    status: "agendado",
    step: "pagamento",
  },
  {
    id: "29",
    sendDate: "26/Maio",
    name: "Item 29",
    priority: true,
    price: "R$ 3.400,00 \n x 1 unidade",
    approvalStep: "1 de 2",
    requirent: "Colaborador 29",
    department: "finance",
    status: "historico",
    step: "pagamento",
  },
  {
    id: "30",
    sendDate: "25/Maio",
    name: "Item 30",
    priority: false,
    price: "R$ 3.500,00 \n x 1 unidade",
    approvalStep: "2 de 2",
    requirent: "Colaborador 30",
    department: "mechanic",
    status: "historico",
    step: "pagamento",
  },
];
