export type Status =
  | "a_pagar"
  | "a_receber"
  | "pendente"
  | "pago"
  | "atrasado"
  | "negado"
  | "incompleto"
  | "recebido";

export interface TransactionProps {
  date: string;
  origin: string;
  value: string;
  type: string;
  category: string;
  cc: string;
  status: Status;
  id: string;
  documents: {
    id: string;
    name: string;
    file: string;
  }[];
}

// Transactions to pay (no "a_receber" or "recebido" statuses)
export type ToPay = TransactionProps;
export const toPay: ToPay[] = [
  {
    date: "2025-07-28",
    origin: "ELECTROLUX DO BRASIL S A",
    value: "R$ 1.200,00",
    type: "toPay",
    category: "Oper - Insumos Operacionais",
    cc: "CC1234",
    status: "a_pagar",
    id: "txn_pay_001",
    documents: [{ id: "doc1", name: "Invoice #123", file: "invoice_123.pdf" }],
  },
  {
    date: "2025-08-02",
    origin: "CASA E VIDEO RIO DE JANEIRO",
    value: "R$ 450,00",
    type: "toPay",
    category: "Oper - Despachantes / Taxas e Serviços Operacionais",
    cc: "CC5678",
    status: "atrasado",
    id: "txn_pay_002",
    documents: [],
  },
  {
    date: "2025-07-25",
    origin: "SAF DO BRASIL PRODUTOS ALIMENTICIOS LTDA",
    value: "R$ 800,00",
    type: "toPay",
    category: "Oper - Manutenção de Equipamentos",
    cc: "CC9012",
    status: "pendente",
    id: "txn_pay_003",
    documents: [{ id: "doc2", name: "Work Order", file: "work_order.pdf" }],
  },
  {
    date: "2025-08-05",
    origin: "TK ELEVADORES BRASIL LTDA",
    value: "R$ 2.500,00",
    type: "toPay",
    category: "Oper - Locação de Equipamentos",
    cc: "CC3456",
    status: "incompleto",
    id: "txn_pay_004",
    documents: [],
  },
  {
    date: "2025-07-23",
    origin: "TP-LINK SISTEMAS DO BRASIL LTDA",
    value: "R$ 3.000,00",
    type: "toPay",
    category: "Oper - Despachantes / Taxas e Serviços Operacionais",
    cc: "CC7890",
    status: "negado",
    id: "txn_pay_005",
    documents: [{ id: "doc3", name: "Contract", file: "contract.pdf" }],
  },
  {
    date: "2025-07-29",
    origin: "SHE OPL VOTORANTIM CIMENTOS SA",
    value: "R$ 950,00",
    type: "toPay",
    category: "Oper - Movimentação de Cargas",
    cc: "CC1111",
    status: "a_pagar",
    id: "txn_pay_006",
    documents: [],
  },
  {
    date: "2025-08-06",
    origin: "Potencial Fomento Mercantil Eireli",
    value: "R$ 600,00",
    type: "toPay",
    category: "Oper - Insumos Operacionais",
    cc: "CC2222",
    status: "pendente",
    id: "txn_pay_007",
    documents: [],
  },
  {
    date: "2025-08-10",
    origin: "Itau Administradora de Consorcios Ltda",
    value: "R$ 1.500,00",
    type: "toPay",
    category: "Oper - Despachantes / Taxas e Serviços Operacionais",
    cc: "CC3333",
    status: "pago",
    id: "txn_pay_008",
    documents: [
      { id: "doc4", name: "Service Report", file: "service_report.pdf" },
    ],
  },
  {
    date: "2025-07-30",
    origin: "Bradesco Administradora de Consorcios Ltda.",
    value: "R$ 750,00",
    type: "toPay",
    category: "Oper - Carga / Descarga / Ajudantes",
    cc: "CC4444",
    status: "a_pagar",
    id: "txn_pay_009",
    documents: [],
  },
  {
    date: "2025-08-07",
    origin: "Itau Unibanco S.a.",
    value: "R$ 1.800,00",
    type: "toPay",
    category: "Oper - Contratação Fretes Terceiro",
    cc: "CC5555",
    status: "atrasado",
    id: "txn_pay_010",
    documents: [],
  },
  {
    date: "2025-07-31",
    origin: "Banco Bradesco S.a.",
    value: "R$ 10.000,00",
    type: "toPay",
    category: "Corp - Impostos a Recolher",
    cc: "CC6666",
    status: "pago",
    id: "txn_pay_011",
    documents: [
      { id: "doc5", name: "Lease Agreement", file: "lease_agreement.pdf" },
    ],
  },
  {
    date: "2025-08-08",
    origin: "Bradesco Auto/re Companhia de Seguros",
    value: "R$ 3.500,00",
    type: "toPay",
    category: "Oper - Fechamento Agregados",
    cc: "CC7777",
    status: "incompleto",
    id: "txn_pay_012",
    documents: [],
  },
  {
    date: "2025-07-26",
    origin: "Secretaria de Estado De Economia do Distrito Federal",
    value: "R$ 2.200,00",
    type: "toPay",
    category: "Oper - Despachantes / Taxas e Serviços Operacionais",
    cc: "CC8888",
    status: "negado",
    id: "txn_pay_013",
    documents: [],
  },
  {
    date: "2025-08-09",
    origin: "ELECTROLUX DO BRASIL S A",
    value: "R$ 1.000,00",
    type: "toPay",
    category: "Oper - Insumos Operacionais",
    cc: "CC9999",
    status: "pendente",
    id: "txn_pay_014",
    documents: [
      { id: "doc6", name: "Printing Invoice", file: "printing_invoice.pdf" },
    ],
  },
  {
    date: "2025-07-27",
    origin: "CASA E VIDEO RIO DE JANEIRO",
    value: "R$ 350,00",
    type: "toPay",
    category: "Oper - Despachantes / Taxas e Serviços Operacionais",
    cc: "CC0000",
    status: "a_pagar",
    id: "txn_pay_015",
    documents: [],
  },
  {
    date: "2025-08-11",
    origin: "SAF DO BRASIL PRODUTOS ALIMENTICIOS LTDA",
    value: "R$ 700,00",
    type: "toPay",
    category: "Oper - Multas de Transporte",
    cc: "CC1010",
    status: "atrasado",
    id: "txn_pay_016",
    documents: [],
  },
  {
    date: "2025-07-24",
    origin: "TK ELEVADORES BRASIL LTDA",
    value: "R$ 2.700,00",
    type: "toPay",
    category: "Oper - Locação de Equipamentos",
    cc: "CC1212",
    status: "pago",
    id: "txn_pay_017",
    documents: [
      { id: "doc7", name: "Supply Invoice", file: "supply_invoice.pdf" },
    ],
  },
  {
    date: "2025-08-12",
    origin: "TP-LINK SISTEMAS DO BRASIL LTDA",
    value: "R$ 150,00",
    type: "toPay",
    category: "Oper - Contratação Fretes Terceiro",
    cc: "CC1313",
    status: "incompleto",
    id: "txn_pay_018",
    documents: [],
  },
  {
    date: "2025-07-21",
    origin: "SHE OPL VOTORANTIM CIMENTOS SA",
    value: "R$ 5.000,00",
    type: "toPay",
    category: "Folha - PJs Contratados",
    cc: "CC1414",
    status: "negado",
    id: "txn_pay_019",
    documents: [],
  },
  {
    date: "2025-08-03",
    origin: "Potencial Fomento Mercantil Eireli",
    value: "R$ 2.300,00",
    type: "toPay",
    category: "Folha - Programação Mensal",
    cc: "CC1515",
    status: "pendente",
    id: "txn_pay_020",
    documents: [
      { id: "doc8", name: "License Invoice", file: "license_invoice.pdf" },
    ],
  },
  {
    date: "2025-08-03",
    origin: "Itau Administradora de Consorcios Ltda",
    value: "R$ 2.300,00",
    type: "toPay",
    category: "Folha - Programação Mensal",
    cc: "CC1515",
    status: "pendente",
    id: "txn_pay_021",
    documents: [
      { id: "doc8", name: "License Invoice", file: "license_invoice.pdf" },
    ],
  },
  {
    date: "2025-08-03",
    origin: "Bradesco Administradora de Consorcios Ltda.",
    value: "R$ 2.300,00",
    type: "toPay",
    category: "Folha - Programação Mensal",
    cc: "CC1515",
    status: "pendente",
    id: "txn_pay_022",
    documents: [
      { id: "doc8", name: "License Invoice", file: "license_invoice.pdf" },
    ],
  },
];

export type ToReceive = TransactionProps;
export const toReceive: ToReceive[] = [
  {
    date: "2025-07-30",
    origin: "ELECTROLUX DO BRASIL S A",
    value: "R$ 5.000,00",
    type: "toReceive",
    category: "Receitas - Faturamento Clientes(+)",
    cc: "CC4321",
    status: "a_receber",
    id: "txn_rec_001",
    documents: [],
  },
  {
    date: "2025-08-01",
    origin: "CASA E VIDEO RIO DE JANEIRO",
    value: "R$ 7.500,00",
    type: "toReceive",
    category: "Provisão - Créditos Armazenagens(+)",
    cc: "CC8765",
    status: "recebido",
    id: "txn_rec_002",
    documents: [{ id: "doc4", name: "Receipt", file: "receipt.pdf" }],
  },
  {
    date: "2025-07-22",
    origin: "SAF DO BRASIL PRODUTOS ALIMENTICIOS LTDA",
    value: "R$ 2.200,00",
    type: "toReceive",
    category: "Provisão - Créditos Frete Retorno(+)",
    cc: "CC2109",
    status: "pendente",
    id: "txn_rec_003",
    documents: [],
  },
  {
    date: "2025-08-08",
    origin: "TK ELEVADORES BRASIL LTDA",
    value: "R$ 1.350,00",
    type: "toReceive",
    category: "Provisão - Dedução Impostos de Faturamento(-)",
    cc: "CC6543",
    status: "atrasado",
    id: "txn_rec_004",
    documents: [],
  },
  {
    date: "2025-07-27",
    origin: "TP-LINK SISTEMAS DO BRASIL LTDA",
    value: "R$ 950,00",
    type: "toReceive",
    category: "Provisão - Bloqueios e Estornos Faturamento(-)",
    cc: "CC0987",
    status: "incompleto",
    id: "txn_rec_005",
    documents: [{ id: "doc5", name: "Order", file: "order.pdf" }],
  },
  {
    date: "2025-08-15",
    origin: "SHE OPL VOTORANTIM CIMENTOS SA",
    value: "R$ 3.500,00",
    type: "toReceive",
    category: "Receitas - Faturamento Clientes(+)",
    cc: "CC1234",
    status: "a_receber",
    id: "txn_rec_006",
    documents: [],
  },
  {
    date: "2025-08-18",
    origin: "Potencial Fomento Mercantil Eireli",
    value: "R$ 2.150,00",
    type: "toReceive",
    category: "Provisão - Créditos Impostos(+)",
    cc: "CC5678",
    status: "pendente",
    id: "txn_rec_007",
    documents: [],
  },
  {
    date: "2025-08-25",
    origin: "Itau Administradora de Consorcios Ltda",
    value: "R$ 4.000,00",
    type: "toReceive",
    category: "Receitas - Faturamento Clientes(+)",
    cc: "CC9012",
    status: "recebido",
    id: "txn_rec_008",
    documents: [{ id: "doc6", name: "Invoice", file: "invoice.pdf" }],
  },
  {
    date: "2025-08-28",
    origin: "Bradesco Administradora de Consorcios Ltda.",
    value: "R$ 1.900,00",
    type: "toReceive",
    category: "Provisão - Créditos Armazenagens(+)",
    cc: "CC1111",
    status: "atrasado",
    id: "txn_rec_009",
    documents: [],
  },
  {
    date: "2025-08-31",
    origin: "Itau Unibanco S.a.",
    value: "R$ 6.000,00",
    type: "toReceive",
    category: "Receitas - Faturamento Clientes(+)",
    cc: "CC2222",
    status: "incompleto",
    id: "txn_rec_010",
    documents: [{ id: "doc7", name: "Proposal", file: "proposal.pdf" }],
  },
  {
    date: "2025-08-04",
    origin: "Banco Bradesco S.a.",
    value: "R$ 1.600,00",
    type: "toReceive",
    category: "Provisão - Créditos Frete Retorno(+)",
    cc: "CC3333",
    status: "a_receber",
    id: "txn_rec_011",
    documents: [],
  },
  {
    date: "2025-08-06",
    origin: "Bradesco Auto/re Companhia de Seguros",
    value: "R$ 3.000,00",
    type: "toReceive",
    category: "Provisão - Dedução Impostos de Faturamento(-)",
    cc: "CC4444",
    status: "pendente",
    id: "txn_rec_012",
    documents: [],
  },
  {
    date: "2025-08-12",
    origin: "Secretaria de Estado De Economia do Distrito Federal",
    value: "R$ 2.500,00",
    type: "toReceive",
    category: "Receitas - Faturamento Clientes(+)",
    cc: "CC5555",
    status: "recebido",
    id: "txn_rec_013",
    documents: [{ id: "doc8", name: "Bill", file: "bill.pdf" }],
  },
  {
    date: "2025-08-19",
    origin: "ELECTROLUX DO BRASIL S A",
    value: "R$ 1.000,00",
    type: "toReceive",
    category: "Provisão - Créditos Impostos(+)",
    cc: "CC6666",
    status: "atrasado",
    id: "txn_rec_014",
    documents: [],
  },
  {
    date: "2025-08-26",
    origin: "CASA E VIDEO RIO DE JANEIRO",
    value: "R$ 4.500,00",
    type: "toReceive",
    category: "Provisão - Bloqueios e Estornos Faturamento(-)",
    cc: "CC7777",
    status: "incompleto",
    id: "txn_rec_015",
    documents: [{ id: "doc9", name: "Enrollment", file: "enrollment.pdf" }],
  },
  {
    date: "2025-08-29",
    origin: "SAF DO BRASIL PRODUTOS ALIMENTICIOS LTDA",
    value: "R$ 3.800,00",
    type: "toReceive",
    category: "Receitas - Faturamento Clientes(+)",
    cc: "CC8888",
    status: "a_receber",
    id: "txn_rec_016",
    documents: [],
  },
  {
    date: "2025-09-01",
    origin: "TK ELEVADORES BRASIL LTDA",
    value: "R$ 2.300,00",
    type: "toReceive",
    category: "Provisão - Créditos Frete Retorno(+)",
    cc: "CC9999",
    status: "pendente",
    id: "txn_rec_017",
    documents: [],
  },
  {
    date: "2025-09-04",
    origin: "TP-LINK SISTEMAS DO BRASIL LTDA",
    value: "R$ 6.500,00",
    type: "toReceive",
    category: "Provisão - Dedução Impostos de Faturamento(-)",
    cc: "CC1010",
    status: "recebido",
    id: "txn_rec_018",
    documents: [
      { id: "doc10", name: "Purchase Order", file: "purchase_order.pdf" },
    ],
  },
  {
    date: "2025-09-07",
    origin: "SHE OPL VOTORANTIM CIMENTOS SA",
    value: "R$ 1.200,00",
    type: "toReceive",
    category: "Provisão - Créditos Impostos(+)",
    cc: "CC1212",
    status: "atrasado",
    id: "txn_rec_019",
    documents: [],
  },
  {
    date: "2025-09-10",
    origin: "Potencial Fomento Mercantil Eireli",
    value: "R$ 3.000,00",
    type: "toReceive",
    category: "Provisão - Bloqueios e Estornos Faturamento(-)",
    cc: "CC1313",
    status: "incompleto",
    id: "txn_rec_020",
    documents: [
      { id: "doc11", name: "Lease Agreement", file: "lease_agreement.pdf" },
    ],
  },
];
