const today = new Date();
const y = today.getFullYear();
const m = today.getMonth();
// const d = today.getDate();

export interface EventType2 {
  id: string;
  type: "Recorrentes" | "Avulso" | "Colaborador";
  movementType: "Entrada" | "Saida";
  status:
    | "À Pagar"
    | "À Receber"
    | "Pendente"
    | "Atrasado"
    | "Pago"
    | "Recebido";
  value: string;
  name: string;
  installments?: string;
  start: Date;
  end: Date;
  color: string;
}
export const Events2: EventType2[] = [
  {
    id: "1",
    type: "Recorrentes",
    status: "À Receber",
    movementType: "Entrada",
    value: "R$ 1.500,20",
    name: "Salário",
    installments: "1/12",
    start: new Date(y, m, 1),
    end: new Date(y, m, 1),
    color: "#d96927",
  },
  {
    id: "2",
    type: "Recorrentes",
    status: "Pendente",
    movementType: "Saida",
    value: "R$ 300,00",
    name: "Assinatura software",
    installments: "2/6",
    start: new Date(y, m, 2),
    end: new Date(y, m, 2),
    color: "#b33f40",
  },
  {
    id: "3",
    type: "Recorrentes",
    status: "Atrasado",
    movementType: "Entrada",
    value: "R$ 1.200,54",
    name: "Comissão mensal",
    start: new Date(y, m, 3),
    end: new Date(y, m, 3),
    color: "#2e86ab",
  },
  {
    id: "4",
    type: "Recorrentes",
    status: "Pago",
    movementType: "Saida",
    value: "R$ 800,00",
    name: "Aluguel da sala",
    installments: "3/12",
    start: new Date(y, m, 4),
    end: new Date(y, m, 4),
    color: "#8e44ad",
  },
  {
    id: "5",
    type: "Recorrentes",
    status: "Atrasado",
    movementType: "Entrada",
    value: "R$ 2.000,00",
    name: "Bônus de desempenho",
    start: new Date(y, m, 5),
    end: new Date(y, m, 5),
    color: "#16a085",
  },
  {
    id: "6",
    type: "Recorrentes",
    status: "Pago",
    movementType: "Saida",
    value: "R$ 450,00",
    name: "Internet corporativa",
    start: new Date(y, m, 6),
    end: new Date(y, m, 6),
    color: "#f39c12",
  },
  {
    id: "7",
    type: "Recorrentes",
    status: "À Receber",
    movementType: "Entrada",
    value: "R$ 3.500,00",
    name: "Pagamento cliente X",
    installments: "4/10",
    start: new Date(y, m, 7),
    end: new Date(y, m, 7),
    color: "#2980b9",
  },
  {
    id: "8",
    type: "Recorrentes",
    status: "Pendente",
    movementType: "Saida",
    value: "R$ 1.000,00",
    name: "Manutenção técnica",
    start: new Date(y, m, 8),
    end: new Date(y, m, 8),
    color: "#c0392b",
  },
  {
    id: "9",
    type: "Recorrentes",
    status: "À Receber",
    movementType: "Entrada",
    value: "R$ 700,00",
    name: "Investimento mensal",
    installments: "1/3",
    start: new Date(y, m, 9),
    end: new Date(y, m, 9),
    color: "#27ae60",
  },
  {
    id: "10",
    type: "Recorrentes",
    status: "Pago",
    movementType: "Saida",
    value: "R$ 600,00",
    name: "Serviços terceirizados",
    start: new Date(y, m, 10),
    end: new Date(y, m, 10),
    color: "#7f8c8d",
  },
  {
    id: "11",
    type: "Recorrentes",
    status: "Atrasado",
    movementType: "Entrada",
    value: "R$ 950,00",
    name: "Retorno de aplicação",
    start: new Date(y, m, 11),
    end: new Date(y, m, 11),
    color: "#9b59b6",
  },
  {
    id: "12",
    type: "Recorrentes",
    status: "Pendente",
    movementType: "Saida",
    value: "R$ 550,00",
    name: "Compra de materiais",
    installments: "5/8",
    start: new Date(y, m, 12),
    end: new Date(y, m, 12),
    color: "#e74c3c",
  },
  {
    id: "13",
    type: "Recorrentes",
    status: "Recebido",
    movementType: "Entrada",
    value: "R$ 1.300,00",
    name: "Reembolso fornecedor",
    start: new Date(y, m, 13),
    end: new Date(y, m, 13),
    color: "#3498db",
  },
  {
    id: "14",
    type: "Recorrentes",
    status: "À Pagar",
    movementType: "Saida",
    value: "R$ 250,00",
    name: "Transporte corporativo",
    start: new Date(y, m, 14),
    end: new Date(y, m, 14),
    color: "#1abc9c",
  },
  {
    id: "15",
    type: "Recorrentes",
    status: "Recebido",
    movementType: "Entrada",
    value: "R$ 1.750,00",
    name: "Receita de consultoria",
    start: new Date(y, m, 15),
    end: new Date(y, m, 15),
    color: "#f1c40f",
  },
  {
    id: "16",
    type: "Recorrentes",
    status: "Atrasado",
    movementType: "Saida",
    value: "R$ 680,00",
    name: "Conta de energia",
    start: new Date(y, m, 16),
    end: new Date(y, m, 16),
    color: "#d35400",
  },
  {
    id: "17",
    type: "Recorrentes",
    status: "Pendente",
    movementType: "Entrada",
    value: "R$ 500,00",
    name: "Reembolso viagem",
    start: new Date(y, m, 17),
    end: new Date(y, m, 17),
    color: "#34495e",
  },
  {
    id: "18",
    type: "Recorrentes",
    status: "À Pagar",
    movementType: "Saida",
    value: "R$ 900,00",
    name: "Seguro patrimonial",
    start: new Date(y, m, 18),
    end: new Date(y, m, 18),
    color: "#95a5a6",
  },
  {
    id: "19",
    type: "Recorrentes",
    status: "Recebido",
    movementType: "Entrada",
    value: "R$ 2.200,00",
    name: "Venda de serviço",
    start: new Date(y, m, 19),
    end: new Date(y, m, 19),
    color: "#e67e22",
  },
  {
    id: "20",
    type: "Recorrentes",
    status: "Atrasado",
    movementType: "Saida",
    value: "R$ 720,00",
    name: "Telefonia empresarial",
    start: new Date(y, m, 20),
    end: new Date(y, m, 20),
    color: "#ec7063",
  },
  {
    id: "21",
    type: "Avulso",
    status: "À Pagar",
    movementType: "Saida",
    value: "R$ 980,00",
    name: "Venda pontual",
    start: new Date(y, m, 1),
    end: new Date(y, m, 1),
    color: "#1abc9c",
  },
  {
    id: "22",
    type: "Avulso",
    status: "Pendente",
    movementType: "Entrada",
    value: "R$ 320,00",
    name: "Compra emergencial",
    start: new Date(y, m, 2),
    end: new Date(y, m, 2),
    color: "#e74c3c",
  },
  {
    id: "23",
    type: "Avulso",
    status: "Atrasado",
    movementType: "Saida",
    value: "R$ 1.250,00",
    name: "Freelancer pago",
    start: new Date(y, m, 3),
    end: new Date(y, m, 3),
    color: "#8e44ad",
  },
  {
    id: "24",
    type: "Avulso",
    status: "Recebido",
    movementType: "Entrada",
    value: "R$ 410,00",
    name: "Peças de reposição",
    start: new Date(y, m, 4),
    end: new Date(y, m, 4),
    color: "#3498db",
  },
  {
    id: "25",
    type: "Avulso",
    status: "À Pagar",
    movementType: "Saida",
    value: "R$ 600,00",
    name: "Serviço eventual",
    start: new Date(y, m, 5),
    end: new Date(y, m, 5),
    color: "#f1c40f",
  },
  {
    id: "26",
    type: "Avulso",
    status: "Pendente",
    movementType: "Entrada",
    value: "R$ 150,00",
    name: "Táxi",
    start: new Date(y, m, 6),
    end: new Date(y, m, 6),
    color: "#d35400",
  },
  {
    id: "27",
    type: "Avulso",
    status: "Pago",
    movementType: "Saida",
    value: "R$ 2.000,00",
    name: "Projeto único",
    start: new Date(y, m, 7),
    end: new Date(y, m, 7),
    color: "#2ecc71",
  },
  {
    id: "28",
    type: "Avulso",
    status: "Atrasado",
    movementType: "Entrada",
    value: "R$ 700,00",
    name: "Consultoria externa",
    start: new Date(y, m, 8),
    end: new Date(y, m, 8),
    color: "#9b59b6",
  },
  {
    id: "29",
    type: "Avulso",
    status: "À Pagar",
    movementType: "Saida",
    value: "R$ 1.100,00",
    name: "Receita extra",
    start: new Date(y, m, 9),
    end: new Date(y, m, 9),
    color: "#34495e",
  },
  {
    id: "30",
    type: "Avulso",
    status: "Recebido",
    movementType: "Entrada",
    value: "R$ 500,00",
    name: "Hospedagem evento",
    start: new Date(y, m, 10),
    end: new Date(y, m, 10),
    color: "#95a5a6",
  },
  {
    id: "31",
    type: "Avulso",
    status: "Pendente",
    movementType: "Saida",
    value: "R$ 850,00",
    name: "Pagamento indevido",
    start: new Date(y, m, 11),
    end: new Date(y, m, 11),
    color: "#7f8c8d",
  },
  {
    id: "32",
    type: "Avulso",
    status: "Atrasado",
    movementType: "Entrada",
    value: "R$ 900,00",
    name: "Compra promocional",
    start: new Date(y, m, 12),
    end: new Date(y, m, 12),
    color: "#f39c12",
  },
  {
    id: "33",
    type: "Avulso",
    status: "Pago",
    movementType: "Saida",
    value: "R$ 1.300,00",
    name: "Aporte avulso",
    start: new Date(y, m, 13),
    end: new Date(y, m, 13),
    color: "#16a085",
  },
  {
    id: "34",
    type: "Avulso",
    status: "À Receber",
    movementType: "Entrada",
    value: "R$ 200,00",
    name: "Material temporário",
    start: new Date(y, m, 14),
    end: new Date(y, m, 14),
    color: "#c0392b",
  },
  {
    id: "35",
    type: "Avulso",
    status: "Pendente",
    movementType: "Saida",
    value: "R$ 1.000,00",
    name: "Reembolso errado",
    start: new Date(y, m, 15),
    end: new Date(y, m, 15),
    color: "#27ae60",
  },
  {
    id: "36",
    type: "Avulso",
    status: "Atrasado",
    movementType: "Entrada",
    value: "R$ 650,00",
    name: "Compra fora do ciclo",
    start: new Date(y, m, 16),
    end: new Date(y, m, 16),
    color: "#2980b9",
  },
  {
    id: "37",
    type: "Avulso",
    status: "Pago",
    movementType: "Saida",
    value: "R$ 1.700,00",
    name: "Venda avulsa",
    start: new Date(y, m, 17),
    end: new Date(y, m, 17),
    color: "#d35400",
  },
  {
    id: "38",
    type: "Avulso",
    status: "À Receber",
    movementType: "Entrada",
    value: "R$ 420,00",
    name: "Custos de urgência",
    start: new Date(y, m, 18),
    end: new Date(y, m, 18),
    color: "#e67e22",
  },
  {
    id: "39",
    type: "Avulso",
    status: "Pendente",
    movementType: "Saida",
    value: "R$ 560,00",
    name: "Recebimento inesperado",
    start: new Date(y, m, 19),
    end: new Date(y, m, 19),
    color: "#bdc3c7",
  },
  {
    id: "40",
    type: "Avulso",
    status: "Atrasado",
    movementType: "Entrada",
    value: "R$ 730,00",
    name: "Taxa emergencial",
    start: new Date(y, m, 20),
    end: new Date(y, m, 20),
    color: "#a569bd",
  },
  {
    id: "41",
    type: "Colaborador",
    status: "À Pagar",
    movementType: "Saida",
    value: "R$ 450,00",
    name: "Transporte excepcional",
    start: new Date(y, m, 18),
    end: new Date(y, m, 18),
    color: "#f1948a",
  },
  {
    id: "42",
    type: "Colaborador",
    status: "À Receber",
    movementType: "Entrada",
    value: "R$ 2.000,00",
    name: "Adiantamento salário",
    start: new Date(y, m, 1),
    end: new Date(y, m, 1),
    color: "#27ae60",
  },
  {
    id: "43",
    type: "Colaborador",
    status: "Pendente",
    movementType: "Entrada",
    value: "R$ 900,00",
    name: "Erro folha anterior",
    start: new Date(y, m, 15),
    end: new Date(y, m, 15),
    color: "#bdc3c7",
  },
  {
    id: "44",
    type: "Colaborador",
    status: "Recebido",
    movementType: "Entrada",
    value: "R$ 800,00",
    name: "Meta batida",
    start: new Date(y, m, 13),
    end: new Date(y, m, 13),
    color: "#34495e",
  },
  {
    id: "45",
    type: "Colaborador",
    status: "Pendente",
    movementType: "Saida",
    value: "R$ 180,00",
    name: "Reembolso recusado",
    start: new Date(y, m, 2),
    end: new Date(y, m, 2),
    color: "#c0392b",
  },
  {
    id: "46",
    type: "Colaborador",
    status: "Recebido",
    movementType: "Entrada",
    value: "R$ 300,00",
    name: "Campanha interna",
    start: new Date(y, m, 19),
    end: new Date(y, m, 19),
    color: "#7dcea0",
  },
  {
    id: "47",
    type: "Colaborador",
    status: "Atrasado",
    movementType: "Entrada",
    value: "R$ 300,00",
    name: "Horas extras",
    start: new Date(y, m, 3),
    end: new Date(y, m, 3),
    color: "#2980b9",
  },
  {
    id: "48",
    type: "Colaborador",
    status: "Pendente",
    movementType: "Entrada",
    value: "R$ 270,00",
    name: "Reposição de equipamento",
    start: new Date(y, m, 11),
    end: new Date(y, m, 11),
    color: "#9b59b6",
  },
  {
    id: "49",
    type: "Colaborador",
    status: "Pago",
    movementType: "Saida",
    value: "R$ 250,00",
    name: "Ajuda de custo",
    start: new Date(y, m, 6),
    end: new Date(y, m, 6),
    color: "#16a085",
  },
  {
    id: "50",
    type: "Colaborador",
    status: "À Receber",
    movementType: "Entrada",
    value: "R$ 500,00",
    name: "Premiação interna",
    start: new Date(y, m, 5),
    end: new Date(y, m, 5),
    color: "#8e44ad",
  },
  {
    id: "51",
    type: "Colaborador",
    status: "Recebido",
    movementType: "Entrada",
    value: "R$ 650,00",
    name: "Bônus produtividade",
    start: new Date(y, m, 9),
    end: new Date(y, m, 9),
    color: "#d35400",
  },
  {
    id: "52",
    type: "Colaborador",
    status: "Atrasado",
    movementType: "Saida",
    value: "R$ 220,00",
    name: "Despesas viagem",
    start: new Date(y, m, 8),
    end: new Date(y, m, 8),
    color: "#1abc9c",
  },
  {
    id: "53",
    type: "Colaborador",
    status: "Pago",
    movementType: "Saida",
    value: "R$ 120,00",
    name: "Vale transporte",
    start: new Date(y, m, 4),
    end: new Date(y, m, 4),
    color: "#f39c12",
  },
  {
    id: "54",
    type: "Colaborador",
    status: "Atrasado",
    movementType: "Entrada",
    value: "R$ 1.100,00",
    name: "Gratificação especial",
    start: new Date(y, m, 17),
    end: new Date(y, m, 17),
    color: "#a569bd",
  },
  {
    id: "55",
    type: "Colaborador",
    status: "À Pagar",
    movementType: "Saida",
    value: "R$ 130,00",
    name: "Vale refeição",
    start: new Date(y, m, 14),
    end: new Date(y, m, 14),
    color: "#f1c40f",
  },
  {
    id: "56",
    type: "Colaborador",
    status: "Pendente",
    movementType: "Saida",
    value: "R$ 210,00",
    name: "Material individual",
    start: new Date(y, m, 20),
    end: new Date(y, m, 20),
    color: "#dc7633",
  },
  {
    id: "57",
    type: "Colaborador",
    status: "Pendente",
    movementType: "Entrada",
    value: "R$ 400,00",
    name: "Solicitação extra",
    start: new Date(y, m, 7),
    end: new Date(y, m, 7),
    color: "#e74c3c",
  },
  {
    id: "58",
    type: "Colaborador",
    status: "Atrasado",
    movementType: "Saida",
    value: "R$ 360,00",
    name: "Curso interno",
    start: new Date(y, m, 12),
    end: new Date(y, m, 12),
    color: "#e67e22",
  },
  {
    id: "59",
    type: "Colaborador",
    status: "Pago",
    movementType: "Saida",
    value: "R$ 500,00",
    name: "Ajuda deslocamento",
    start: new Date(y, m, 16),
    end: new Date(y, m, 16),
    color: "#5dade2",
  },
  {
    id: "60",
    type: "Colaborador",
    status: "À Receber",
    movementType: "Entrada",
    value: "R$ 300,00",
    name: "Uniformes",
    start: new Date(y, m, 10),
    end: new Date(y, m, 10),
    color: "#7f8c8d",
  },
];
